name:                praxis-effect-resolution
version:             0.1.0.0
github:              "mridsole/praxis-effect-resolution"
license:             BSD3
author:              "David Rapisarda"
maintainer:          "mridsole@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: na

dependencies:
- base >= 4.7 && < 5
- containers
- monad-loops

library:
  source-dirs: src

executables:
  praxis-effect-resolution-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - praxis-effect-resolution

tests:
  praxis-effect-resolution-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - praxis-effect-resolution
